
import React, { useState, useEffect } from 'react';
import { HashRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import DashboardHeader from './components/DashboardHeader';
import PublicHome from './pages/PublicHome';
import SessionDetail from './pages/SessionDetail';
import AdminDashboard from './pages/AdminDashboard';
import AdminLogin from './components/AdminLogin';
import { AuthState } from './types';

const App: React.FC = () => {
  const [auth, setAuth] = useState<AuthState>(() => {
    const saved = localStorage.getItem('savvy_auth');
    return saved ? JSON.parse(saved) : { user: null, isAdmin: false };
  });

  const [showLogin, setShowLogin] = useState(false);

  useEffect(() => {
    localStorage.setItem('savvy_auth', JSON.stringify(auth));
  }, [auth]);

  const handleLogin = (success: boolean) => {
    if (success) {
      setAuth({ user: 'savvysocietyteam@gmail.com', isAdmin: true });
      setShowLogin(false);
    }
  };

  const handleLogout = () => {
    setAuth({ user: null, isAdmin: false });
    window.location.hash = '#/';
  };

  return (
    <Router>
      <div className="min-h-screen bg-slate-50">
        <DashboardHeader 
          isAdmin={auth.isAdmin} 
          onLogout={handleLogout} 
          onLogin={() => setShowLogin(true)} 
        />
        
        <main>
          <Routes>
            <Route path="/" element={<PublicHome />} />
            <Route path="/session/:id" element={<SessionDetail />} />
            <Route 
              path="/admin" 
              element={auth.isAdmin ? <AdminDashboard /> : <Navigate to="/" />} 
            />
          </Routes>
        </main>

        {showLogin && (
          <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
            <div className="bg-white rounded-xl shadow-2xl max-w-md w-full p-8 relative">
              <button 
                onClick={() => setShowLogin(false)}
                className="absolute top-4 right-4 text-slate-400 hover:text-slate-600"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
              <AdminLogin onLogin={handleLogin} />
            </div>
          </div>
        )}

        <footer className="bg-white border-t border-slate-200 mt-20 py-12">
          <div className="max-w-7xl mx-auto px-4 text-center">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">
              Savvy Peer-Grade Academic Insight Dashboard &copy; {new Date().getFullYear()}
            </p>
            <p className="text-[10px] text-slate-400 mt-2 max-w-lg mx-auto leading-relaxed">
              Designed for institutional research and collective data visualization. Savvy provides descriptive analysis of aggregated student survey data. No personal advice or predictive results are generated by this system.
            </p>
          </div>
        </footer>
      </div>
    </Router>
  );
};

export default App;
